### ISSUE TITLE
Compatibility tools shows as unused. Can't see Game List.

### ISSUE THREAD

**Issue by KawaiiDinosaur** [DavidoTek/ProtonUp-Qt#160]
Every compatibility tool is show as unused, despite being used in Steam. Also, clicking the "show game list" button does nothing.

```
ProtonUp-Qt 2.7.6 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.10.6 (main, Nov 10 2011, 15:00:00) [GCC 12.1.0], PySide 6.4.0.1
Platform: Linux-6.0.12-arch1-1-x86_64-with-glibc2.35
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Proton Tkg
Loaded ctmod Roberta
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2.py", line 288, in btn_show_game_list_clicked
    gl_dialog = PupguiGameListDialog(install_directory(), self.ui)
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2gamelistdialog.py", line 34, in __init__
    self.setup_ui()
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2gamelistdialog.py", line 47, in setup_ui
    self.update_game_list_steam()
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2gamelistdialog.py", line 68, in update_game_list_steam
    for t in get_steam_ctool_list(steam_config_folder=self.install_loc.get('vdf_dir')):
  File "/app/lib/python3.10/site-packages/pupgui2/steamutil.py", line 88, in get_steam_ctool_list
    ctool_map = _get_steam_ctool_info(steam_config_folder)
  File "/app/lib/python3.10/site-packages/pupgui2/steamutil.py", line 144, in _get_steam_ctool_info
    for t in compat_tools:
TypeError: 'NoneType' object is not iterable
```
![Screenshot_20221217_201024](https://user-images.githubusercontent.com/36821201/208269369-39e68c44-321e-4d3d-b8de-dda864cdc0d7.png)

**Comment by DavidoTek** [comment]
Duplicate of https://github.com/DavidoTek/ProtonUp-Qt/issues/155

There was a change to the steam dependency, it will be fixed in the next release. I will keep this issue open until it is fixed.

**Comment by BillFleming** [comment]
Is there a specific new dependency that we need to install/remove after updating to the new version? I am getting this bug (game list button) on 2.7.7 still. Did fresh build today on arch, then uninstalled and re-installed and it is still occuring. Did full arch system update over the weekend.
```
ProtonUp-Qt 2.7.7 by DavidoTek. Build Info: built from source.
Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0], PySide 6.4.1
Platform: 1.4 Antergos Linux-6.1.1-273-tkg-bore-x86_64-with-glibc2.36
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod NorthStar Proton (TitalFall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute and QSGRendererInterface::OpenGLRhi using QQuickWindow::setGraphicsApi before constructing QGuiApplication.
Gamepad error: No gamepad found.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pupgui2/pupgui2.py", line 304, in btn_show_game_list_clicked
    gl_dialog = PupguiGameListDialog(install_directory(), self.ui)
  File "/usr/lib/python3.10/site-packages/pupgui2/pupgui2gamelistdialog.py", line 34, in __init__
    self.setup_ui()
  File "/usr/lib/python3.10/site-packages/pupgui2/pupgui2gamelistdialog.py", line 48, in setup_ui
    self.update_game_list_steam()
  File "/usr/lib/python3.10/site-packages/pupgui2/pupgui2gamelistdialog.py", line 70, in update_game_list_steam
    ctools.extend(t.ctool_name for t in get_steam_ctool_list(steam_config_folder=self.install_loc.get('vdf_dir')))
  File "/usr/lib/python3.10/site-packages/pupgui2/steamutil.py", line 85, in get_steam_ctool_list
    ctool_map = _get_steam_ctool_info(steam_config_folder)
  File "/usr/lib/python3.10/site-packages/pupgui2/steamutil.py", line 140, in _get_steam_ctool_info
    for t in compat_tools:
TypeError: 'NoneType' object is not iterable
```

**Comment by DavidoTek** [comment]
> Edit: I manually updated aur/python-steam from 1.4.3-1 to 1.4.4-1 and the problem went away. This is a makepkg depends problem.

Yeah, there was a change to the MAGIC (file identifier) of Steam's appinfo.vdf file.
Interesting, so makepkg doesn't update all dependencies when an update for the main package is available?
