### ISSUE TITLE
After pressing on Show Game List nthing happens

### ISSUE THREAD

**Issue by Schmarotzer** [DavidoTek/ProtonUp-Qt#165]
**Describe the bug**  
Show Game list button doing nothing in not SU account

**To Reproduce**  
1. Create another user account (Xubuntu 22.04)
2. Create cooperative group named "store" for me(superuser) and another user.
3. Create folder /store/steamLibrary for us
4. Install ant game (Satisfactory in my case) in my user account
5. In my user account Show Game list button works fine.
6. Logoff my account. Login to another account.
7. Press Show Game list and nothing happens (see terminal output)

**Expected behavior**  

**Screenshots**  

**Desktop (please complete the following information):**  
 - **Platform**: PC
 - **System**: Xubuntu 22.04
 - **Version**: ProtonUp-Qt v2.7.6
 - **How did you install ProtonUp-Qt?**: AppImage

**Additional context**  

**Terminal output**  
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Traceback (most recent call last):
  File "/tmp/.mount_ProtonRUz71r/usr/lib/python3.8/site-packages/pupgui2/pupgui2.py", line 288, in btn_show_game_list_clicked
    gl_dialog = PupguiGameListDialog(install_directory(), self.ui)
  File "/tmp/.mount_ProtonRUz71r/usr/lib/python3.8/site-packages/pupgui2/pupgui2gamelistdialog.py", line 34, in __init__
    self.setup_ui()
  File "/tmp/.mount_ProtonRUz71r/usr/lib/python3.8/site-packages/pupgui2/pupgui2gamelistdialog.py", line 47, in setup_ui
    self.update_game_list_steam()
  File "/tmp/.mount_ProtonRUz71r/usr/lib/python3.8/site-packages/pupgui2/pupgui2gamelistdialog.py", line 68, in update_game_list_steam
    for t in get_steam_ctool_list(steam_config_folder=self.install_loc.get('vdf_dir')):
  File "/tmp/.mount_ProtonRUz71r/usr/lib/python3.8/site-packages/pupgui2/steamutil.py", line 88, in get_steam_ctool_list
    ctool_map = _get_steam_ctool_info(steam_config_folder)
  File "/tmp/.mount_ProtonRUz71r/usr/lib/python3.8/site-packages/pupgui2/steamutil.py", line 144, in _get_steam_ctool_info
    for t in compat_tools:
TypeError: 'NoneType' object is not iterable

**Comment by DavidoTek** [comment]
Same issue as https://github.com/DavidoTek/ProtonUp-Qt/issues/155.

It's already fixed for the Flatpak/App store version. I have released an updated AppImage today (version 2.7.7).
