### ISSUE TITLE
Crash: inputs.UnpluggedError: No gamepad found.

### ISSUE THREAD

**Issue by Eonfge** [DavidoTek/ProtonUp-Qt#21]
```
[kevin@kevin-at-fedora ~]$ flatpak run net.davidotek.pupgui2 
Gtk-Message: 21:45:31.289: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:45:31.289: Failed to load module "pk-gtk-module"
Gtk-Message: 21:45:31.289: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:45:31.290: Failed to load module "pk-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
ProtonUp-Qt 2.4.0 by DavidoTek. Base directory: /app/share/pupgui2
Loaded ctmod Proton-GE
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Roberta
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/inputs.py", line 3676, in get_gamepad
    gamepad = devices.gamepads[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/pupgui2/gamepadinputworker.py", line 16, in run
    events = inputs.get_gamepad()
  File "/app/lib/python3.9/site-packages/inputs.py", line 3678, in get_gamepad
    raise UnpluggedError("No gamepad found.")
inputs.UnpluggedError: No gamepad found.
```

**Comment by pizzadude** [comment]
Same issue here.

**Comment by yochananmarqos** [comment]
Indeed. Why use an unmaintained Python module? `inputs` hasn't been touched for almost three years.

**Comment by pizzadude** [comment]
```
flatpak override --env=PUPGUI2_DISABLE_GAMEPAD=1 net.davidotek.pupgui2 --user
```
fixes the issue for now.

**Comment by DavidoTek** [comment]
Fixed with https://github.com/DavidoTek/ProtonUp-Qt/commit/f730ba4a540826ca7047d37a2304fec3a739a181 (will just handle the exception). Will be included in the next release.
@ yochananmarqos I will have to search for an alternative, any suggestions?

**Comment by yochananmarqos** [comment]
@DavidoTek I don't know of anything better, sorry. I'm just a package maintainer, not a programmer.
