### ISSUE TITLE
Crash on launch when a controller is connected

### ISSUE THREAD

**Issue by strycore** [DavidoTek/ProtonUp-Qt#26]
I get the following crash when I start ProtonUp-Qt with a controller connected:

```
╰─ ./ProtonUp-Qt-2.4.1-x86_64.AppImage                                                                              ─╯
Traceback (most recent call last):
  File "/tmp/.mount_ProtonajEtNN//usr/src/pupgui2/pupgui2.py", line 18, in <module>
    from gamepadinputworker import GamepadInputWorker
  File "/tmp/.mount_ProtonajEtNN/usr/src/pupgui2/gamepadinputworker.py", line 1, in <module>
    import inputs
  File "/tmp/.mount_ProtonajEtNN/usr/lib/python3.8/site-packages/inputs.py", line 3652, in <module>
    devices = DeviceManager()  # pylint: disable=invalid-name
  File "/tmp/.mount_ProtonajEtNN/usr/lib/python3.8/site-packages/inputs.py", line 3188, in __init__
    self._post_init()
  File "/tmp/.mount_ProtonajEtNN/usr/lib/python3.8/site-packages/inputs.py", line 3200, in _post_init
    self._find_leds()
  File "/tmp/.mount_ProtonajEtNN/usr/lib/python3.8/site-packages/inputs.py", line 3359, in _find_leds
    self._parse_led_path(path)
  File "/tmp/.mount_ProtonajEtNN/usr/lib/python3.8/site-packages/inputs.py", line 3364, in _parse_led_path
    self.leds.append(GamepadLED(self, path, name))
  File "/tmp/.mount_ProtonajEtNN/usr/lib/python3.8/site-packages/inputs.py", line 3133, in __init__
    super(GamepadLED, self).__init__(manager, path, name)
  File "/tmp/.mount_ProtonajEtNN/usr/lib/python3.8/site-packages/inputs.py", line 3003, in __init__
    self._post_init()
  File "/tmp/.mount_ProtonajEtNN/usr/lib/python3.8/site-packages/inputs.py", line 3137, in _post_init
    self._character_device_path = self.gamepad.get_char_device_path()
AttributeError: 'NoneType' object has no attribute 'get_char_device_path'
```

The controller is a standard wired Xbox360 controller and this happens on both the AppImage and the Flatpak. The program works great when I disconnect the controller.

**Comment by DavidoTek** [comment]
Looks like some issue with the `inputs` packages https://github.com/zeth/inputs/issues/72. Easiest fix for now probably is to add an exception handler...

I may have to look for an alternative for `inputs` in the future.
