### ISSUE TITLE
pupgui2 IsADirectoryError

### ISSUE THREAD

**Issue by alkaris2** [DavidoTek/ProtonUp-Qt#365]
Please fill out following when reporting a new bug:

**Describe the bug**  
Something clearly isn't working with pupgui2 in the Python Script which returns an `IsADirectoryError`

![image](https://github.com/DavidoTek/ProtonUp-Qt/assets/73155407/23180196-5d7a-4d75-823e-a3c176a61706)

```
$ protonup-qt 
ProtonUp-Qt 2.9.1 by DavidoTek. Build Info: built from source.
Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801], PySide 6.6.1
Platform: ManjaroLinux 23.1.1 Linux-6.5.13-7-MANJARO-x86_64-with-glibc2.38
Loading locale en / en_AU
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Northstar Proton (Titanfall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine)
Loaded ctmod Wine Tkg (Vanilla Wine)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
Gamepad error: No gamepad found.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 359, in btn_show_game_list_clicked
    gl_dialog = PupguiGameListDialog(install_directory(), self.ui)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pupgui2/pupgui2gamelistdialog.py", line 41, in __init__
    self.setup_ui()
  File "/usr/lib/python3.11/site-packages/pupgui2/pupgui2gamelistdialog.py", line 51, in setup_ui
    self.setup_steam_list_ui()
  File "/usr/lib/python3.11/site-packages/pupgui2/pupgui2gamelistdialog.py", line 85, in setup_steam_list_ui
    self.update_game_list_steam()
  File "/usr/lib/python3.11/site-packages/pupgui2/pupgui2gamelistdialog.py", line 157, in update_game_list_steam
    p.loadFromData(pkgutil.get_data(__name__, os.path.join('resources/img', awacy_icon)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pkgutil.py", line 640, in get_data
    return loader.get_data(resource_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
IsADirectoryError: [Errno 21] Is a directory: '/usr/lib/python3.11/site-packages/pupgui2/resources/img/'
```

**To Reproduce**  
1. Open ProtonUp-Qt
2. Click on the button for `Show game list`

**Desktop (please complete the following information):**  
 - **Platform**: PC
 - **System**: Manjaro Linux
 - **Version**: ProtonUp-Qt 2.9.1
 - **How did you install ProtonUp-Qt?**: AUR

**Comment by sonic2kk** [comment]
Does this happen with the Flatpak or AppImage?
