### ISSUE TITLE
Steam not visible and "..." crashes app on first run

### ISSUE THREAD

**Issue by arcanon** [DavidoTek/ProtonUp-Qt#370]
Please fill out following when reporting a new bug:

**Describe the bug**  
./ProtonUp-Qt-2.9.1-x86_64.AppImage 
ProtonUp-Qt 2.9.1 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0], PySide 6.2.4
Platform: Ubuntu 22.04 Linux-6.5.0-14-generic-x86_64-with-glibc2.29
Gtk-Message: 14:41:27.549: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:41:27.556: Failed to load module "canberra-gtk-module"
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Northstar Proton (Titanfall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine)
Loaded ctmod Wine Tkg (Vanilla Wine)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Gamepad error: No gamepad found.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Traceback (most recent call last):
  File "/tmp/.mount_ProtonIvo955/usr/lib/python3.8/site-packages/pupgui2/pupgui2.py", line 381, in btn_manage_install_locations_clicked
    customid_dialog = PupguiCustomInstallDirectoryDialog(install_directory(), parent=self.ui)
  File "/tmp/.mount_ProtonIvo955/usr/lib/python3.8/site-packages/pupgui2/pupgui2customiddialog.py", line 32, in __init__
    self.setup_ui()
  File "/tmp/.mount_ProtonIvo955/usr/lib/python3.8/site-packages/pupgui2/pupgui2customiddialog.py", line 53, in setup_ui
    self.set_selected_launcher(self.install_locations_dict[self.launcher] or 'steam')  # Default combobox selection to "Steam" if unknown launcher for some reason
KeyError: ''

 - **Platform**:  Desktop Ubuntu 22.04
 - **Version**: For example ProtonUp-Qt 2.9.1
 - **How did you install ProtonUp-Qt?**: same error for Flatpak / AppImage

**Comment by sonic2kk** [comment]
Can't reproduce with Flatpak or AppImage v2.9.1, or running from source @ 6cf1def3bf1ee9775b2639ed41aad1ff96ae2afa.

Steam not being visible likely means that ProtonUp-Qt cannot find your Steam installation. Where is Steam installed on your PC?

I think the `KeyError: ''` is coming from Steam not being found, and thus causing a crash. I haven't confirmed this, though.

**Comment by sonic2kk** [comment]
Confirmed that if no valid launchers are found, trying to open the Custom Install Directory dialog results in a crash.

**Comment by sonic2kk** [comment]
The crash should be fixed in v2.9.2 (only available as AppImage right now), although still not sure why ProtonUp-Qt couldn't find Steam.

**Comment by arcanon** [comment]
steam was not installed yet, that was my bad.
