### ISSUE TITLE
proton flatpak version 2.92 UnicodeDecodeError 'utf-8'

### ISSUE THREAD

**Issue by Vergg** [DavidoTek/ProtonUp-Qt#441]
Please fill out following when reporting a new bug:

**Describe the bug**  
Launching Protonup produces a unicode decode error

**To Reproduce**  
1. Launch Proton Up

**Screenshots**  
Error Log Cut/Paste:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/lib/python3.11/site-packages/pupgui2/__main__.py", line 2, in <module>
    main()
  File "/app/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 568, in main
    MainWindow()
  File "/app/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 109, in __init__
    self.update_ui()
  File "/app/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 230, in update_ui
    global_ctool_name: str = get_steam_global_ctool_name(install_loc.get('vdf_dir'))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/pupgui2/steamutil.py", line 221, in get_steam_global_ctool_name
    d = get_steam_vdf_compat_tool_mapping(vdf.load(open(config_vdf_file)))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/vdf/__init__.py", line 211, in load
    return parse(fp, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/vdf/__init__.py", line 97, in parse
    for lineno, line in enumerate(fp, 1):
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 6004: invalid continuation byte

**Desktop (please complete the following information):**  
 - **Platform**: AMD PC
 - **System**: Kubuntu 24.04
 - **Version**: ProtonUp-Qt 2..92
 - **How did you install ProtonUp-Qt?**: Discover app store / Flatpak 
**Additional context**  

I did the same fix that this post did and it did not resolve it: 
https://github.com/DavidoTek/ProtonUp-Qt/issues/424

**Terminal output**  
```
If you installed ProtonUp-Qt via Flatpak (Discover on Steam Deck), type:
flatpak run net.davidotek.pupgui2

pc:~$ flatpak run net.davidotek.pupgui2
ProtonUp-Qt 2.9.2 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.11.9 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0], PySide 6.7.0
Platform: KDE Flatpak runtime 6.7 Linux-6.8.0-40-generic-x86_64-with-glibc2.38
Qt: Session management error: Could not open network socket
Loading locale en / en_CA
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Northstar Proton (Titanfall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine Bleeding Edge)
Loaded ctmod Wine Tkg (Wine Master)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
Error: Could not get a list of all Steam apps: 'utf-8' codec can't decode byte 0xe1 in position 6004: invalid continuation byte
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/lib/python3.11/site-packages/pupgui2/__main__.py", line 2, in <module>
    main()
  File "/app/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 568, in main
    MainWindow()
  File "/app/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 109, in __init__
    self.update_ui()
  File "/app/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 230, in update_ui
    global_ctool_name: str = get_steam_global_ctool_name(install_loc.get('vdf_dir'))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/pupgui2/steamutil.py", line 221, in get_steam_global_ctool_name
    d = get_steam_vdf_compat_tool_mapping(vdf.load(open(config_vdf_file)))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/vdf/__init__.py", line 211, in load
    return parse(fp, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/vdf/__init__.py", line 97, in parse
    for lineno, line in enumerate(fp, 1):
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 6004: invalid continuation byte

Gamepad error: No gamepad found.
QThread: Destroyed while thread is still running
/app/bin/net.davidotek.pupgui2: line 3:     3 Aborted                 (core dumped) python3 -m pupgui2 "$@"


Try to replicate the bug and paste the text output of the command here afterwards.
```

**Comment by DavidoTek** [comment]
Looks similar to issue 424. Please take a look at https://github.com/DavidoTek/ProtonUp-Qt/issues/424#issuecomment-2246753658

The issue is likely caused by a wrongly configured language setting. The linked issue is on Arch Linux, but the steps should be similar. Let me know if the described solution fixed the issue for you.

**Comment by Vergg** [comment]
Yes very similar. I tried the same steps from that one and it didn't help. I was thinking of going over to Linux Mint so I'm just doing that right now as I got tired of troubleshooting Kubuntu. I'm going to mark this as closed for now as I'm no longer able to troubleshoot it.
