### ISSUE TITLE
ProtonUp-Qt doesn't open

### ISSUE THREAD

**Issue by Delor3an91** [DavidoTek/ProtonUp-Qt#475]
ProtonUp-Qt doesn't open, no GUI since last updates of the dependencies.

I'm on CachyOS (Arch based)

Wish You well

**Comment by DavidoTek** [comment]
Please follow the issue template so that we can help you. Also, check https://github.com/DavidoTek/ProtonUp-Qt/wiki/Debugging-ProtonUp%E2%80%90Qt-%E2%80%90-reporting-Issues

<details> 
  <summary>Issue template</summary>
Please fill out following when reporting a new bug:

**Describe the bug**  
A clear and concise description of what the bug is.

**To Reproduce**  
Steps to reproduce the behavior:
1. For example:
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**  
A clear and concise description of what you expected to happen.

**Screenshots**  
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**  
 - **Platform**: Are you using a Steam Deck or a PC/Laptop?
 - **System**: For example SteamOS 3.3 or Lubuntu 20.04
 - **Version**: For example ProtonUp-Qt 2.5.0
 - **How did you install ProtonUp-Qt?**: Discover app store / Flatpak / AppImage

**Additional context**  
Add any other context about the problem here.

**Terminal output**  
```
Open the Terminal app and type one of the following commands and press Enter (The app is called "Konsole" on Steam Deck):

If you installed ProtonUp-Qt via Flatpak (Discover on Steam Deck), type:
flatpak run net.davidotek.pupgui2

If you have downloaded the AppImage, navigate to the folder containing the AppImage file and type:
./ProtonUp-Qt*.AppImage

Try to replicate the bug and paste the text output of the command here afterwards.
``` 
</details>

**Comment by FellowNeighbour** [comment]
This has been happening to me as well on arch.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.13/site-packages/pupgui2/__main__.py", line 1, in <module>
    from pupgui2.pupgui2 import main
  File "/usr/lib/python3.13/site-packages/pupgui2/pupgui2.py", line 18, in <module>
    from pupgui2 import ctloader
  File "/usr/lib/python3.13/site-packages/pupgui2/ctloader.py", line 7, in <module>
    from pupgui2.util import create_msgbox
  File "/usr/lib/python3.13/site-packages/pupgui2/util.py", line 26, in <module>
    from pupgui2.steamutil import remove_steamtinkerlaunch, is_valid_steam_install
  File "/usr/lib/python3.13/site-packages/pupgui2/steamutil.py", line 11, in <module>
    from steam.utils.appcache import parse_appinfo
ModuleNotFoundError: No module named 'steam'

**Comment by cafecitohippo** [comment]
Same for me. Getting this error when trying to launch.

/usr/bin/python: No module named pupgui2

**Comment by DavidoTek** [comment]
Are you using the AUR version of ProtonUp-Qt?

Please try the Flatpak or AppImage version and check if the issue persists.

**Comment by FellowNeighbour** [comment]
> Are you using the AUR version of ProtonUp-Qt?
> 
> Please try the Flatpak or AppImage version and check if the issue persists.

I am infact using the AUR version, yes. I will try the other two options later today.

**Comment by sonic2kk** [comment]
If this is specific to the AUR version, it may be worth following up with the AUR package maintainers.

Note that the AUR package [has some guidance](https://aur.archlinux.org/packages/protonup-qt#comment-951661) on resolving issues, it may be worth following that first to confirm that this is a separate issue than previously reported ones to the AUR package maintainer. To my untrained eye, it looks to be the same issue you are facing @FellowNeighbour. Cannot comment on OP as they did not provide a log.

For users of CachyOS, you may need to follow up with your distribution.

<hr>

@cafecitohippo Your issue looks like you tried to run `python3 -m pupgui2` but the module is not present, which suggests to me your package did not install itself or it's dependencies properly, or you're trying to run from source without cloning the repo.

**Comment by FellowNeighbour** [comment]
> If this is specific to the AUR version, it may be worth following up with the AUR package maintainers.
> 
> Note that the AUR package [has some guidance](https://aur.archlinux.org/packages/protonup-qt#comment-951661) on resolving issues, it may be worth following that first to confirm that this is a separate issue than previously reported ones to the AUR package maintainer. To my untrained eye, it looks to be the same issue you are facing @FellowNeighbour. Cannot comment on OP as they did not provide a log.
> 
> For users of CachyOS, you may need to follow up with your distribution.
> 
> @cafecitohippo Your issue looks like you tried to run `python3 -m pupgui2` but the module is not present, which suggests to me your package did not install itself or it's dependencies properly, or you're trying to run from source without cloning the repo.

You are very much correct. Running 'yay -Rns protonup-qt" followed by 'yay -S protonup-qt' did in fact fix the issue. Thank you. To anyone else using the AUR build of ProtonUp-QT, I suggest trying the above commands.

**Comment by cafecitohippo** [comment]
I am using the AUR version as well. AppImage and Flatpak versions work fine after testing those. I tried "yay -Rns protonup-qt" and then re-installing but still getting the same error. I definitely don't remember doing anything like "python3 -m pupgui2" that would've caused the issue.

**Comment by Delor3an91** [comment]
Hi,

I am using the `protonup-qt` from Arch or CachyOS repo and have this problem. I haven't try to uninstall and reinstall yet but I will and let You know if it solve the problem.

Wish You well

**Comment by sonic2kk** [comment]
@cafecitohippo this sounds like something to report upstream to the packager, as it sounds specific to that package.

@Delor3an91 ProtonUp-Qt is not in the official Arch repos. Check if it is from the AUR or CachyOS repos. It may be best also to report this issue further upstream, though it may be best assume a CachyOS issue first. Good luck!

**Comment by Delor3an91** [comment]
Hi,

I confirm that uninstall `protonup-qt` and all the dependencies and then reinstall it make it work again on CachyOS.

Wish You well
