### ISSUE TITLE
[Bug] Throws exception, if I only use a window manager

### ISSUE THREAD

**Issue by Dummerle** [DavidoTek/ProtonUp-Qt#7]
./ProtonUp-Qt-1.5.0-x86_64.AppImage

> Traceback (most recent call last):
>   File "/tmp/.mount_ProtonHIxb8n//usr/src/pupgui/pupgui.py", line 136, in <module>
>     apply_dark_theme(app)
>   File "/tmp/.mount_ProtonHIxb8n//usr/src/pupgui/pupgui.py", line 102, in apply_dark_theme
>     is_plasma = 'plasma' in os.environ.get('DESKTOP_SESSION')
> TypeError: argument of type 'NoneType' is not iterable
> 

I use i3 as window manager, `DESKTOP_SESSION` environment variable is not set. Maybe you can add a default option: `os.environ.get('DESKTOP_SESSION', [])`

Btw. If you need help with Qt, feel free to ask me. I have some experience

**Comment by Dummerle** [comment]
You have to update the py file every time you update ui file. There can't break anything
